### ISSUE TITLE
Only allow imports and comments in main.css

### ISSUE THREAD

**Issue by maxhoffmann** [diesdasdigital/csslint#12]
Instead of completely disabling linting for `main.css`, which then allows adding random styles to the file, we could treat files named `main.css` in a special way, so that only `@import` and comments are allowed.

**Comment by maxhoffmann** [comment]
I don’t think this is valid anymore after our conversation. It should not be disabled for linting in general.

**Comment by maxhoffmann** [comment]
I thought about it a bit and I think this makes sense but the other way around:
- all imports are disallowed except for `main.css`

This way we have a single entry file which imports everything which leads to a flat and simple hierarchy of imports. Since we treat that file special we could also disallow anything else except for comments and imports…

**Comment by erkal** [comment]
made a PR about this: https://github.com/diesdasdigital/csslint/pull/15

> Since we treat that file special we could also disallow anything else except for comments and imports…

Should we do also this? The PR does not include this.

**Comment by maxhoffmann** [comment]
@erkal Yes let’s do that too. There shouldn’t be a component called “main”. It’s better to do this in a separate PR though.

**Comment by erkal** [comment]
ok, it has been done in this PR: https://github.com/diesdasdigital/csslint/pull/16
I merged it.
You can close this issue, if everything is fine.

**Comment by maxhoffmann** [comment]
🚀Released!
