### ISSUE TITLE
Completely disallow tags

### ISSUE THREAD

**Issue by maxhoffmann** [diesdasdigital/csslint#13]
Currently we have the rule:
- no type selectors (with the only exception `> tag`)

Using `> tag` should be an exception, because it can still lead to components unintentionally overriding other components if they are nested. If one component needs it for specific reasons one can disable that line, but in general it should be prohibited.

**Comment by erkal** [comment]
solved by the PR https://github.com/diesdasdigital/csslint/pull/14
